apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - name: http
      port: 21
      targetPort: 21
    - name: pasv
      port: 10000
      targetPort: 10000
  loadBalancerIP: 192.168.49.233
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: service_ftps
          imagePullPolicy: Never
      restartPolicy: Always